spring:
  datasource:
    password: yhx742446272
    username: root
    url: jdbc:mysql://43.226.148.127:3306/mall
    driver-class-name: com.mysql.cj.jdbc.Driver

    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
  redis:
    host: 43.226.148.127
    password: yhx742446272
    port: 6379

mybatis:
  config-location: classpath:/mybatis/mybatis.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
